// Beta invite-code gate (v4.12.0; G2 cohort flipped on at v4.12.1).
//
// Three primitives:
//   - betaInviteRequired()       env-flag check, used by signup endpoints
//                                + the /signup UI to decide whether to
//                                show the gate at all.
//   - validateInviteCode(code)   read-only check; safe for the public
//                                preflight endpoint. Returns the matching
//                                row's id when usable, else a reason.
//   - redeemInviteCode(id, uid)  transactional redeem — atomically
//                                increments used_count and writes the
//                                redemption row. Throws if the code is
//                                no longer redeemable (race-safe via row
//                                lock). Caller is responsible for tying
//                                this into the same transaction as the
//                                user create (or accepting that a rare
//                                race can over-redeem by 1).
//
// Code format: human-readable BETA-XXXXXXX where XXXXXXX is 7 chars from
// an unambiguous alphabet (no 0/O/1/I). Generated by mintInviteCode().

import { randomBytes } from "node:crypto";
import { prisma } from "@/lib/db";

const ALPHABET = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"; // 32 chars, no 0/O/1/I
const SUFFIX_LEN = 7; // 32^7 ≈ 34B combinations
export const CODE_PREFIX = "BETA-";

export type ValidateResult =
  | { valid: true; codeId: string; remainingUses: number }
  | { valid: false; reason: "NOT_FOUND" | "EXPIRED" | "EXHAUSTED" };

export function betaInviteRequired(): boolean {
  // Both the server-side and NEXT_PUBLIC_ variants flip the gate; this lets
  // us toggle it from a single env-var change without redeploying just to
  // expose it to the client bundle.
  return (
    process.env.BETA_INVITE_REQUIRED === "1" ||
    process.env.NEXT_PUBLIC_BETA_INVITE_REQUIRED === "1"
  );
}

export function generateInviteCode(): string {
  const bytes = randomBytes(SUFFIX_LEN);
  let suffix = "";
  for (let i = 0; i < SUFFIX_LEN; i += 1) {
    suffix += ALPHABET[bytes[i] % ALPHABET.length];
  }
  return `${CODE_PREFIX}${suffix}`;
}

/**
 * Normalize user input — uppercase, trim, strip stray whitespace inside.
 * Preserves the BETA- prefix if missing (some users may paste only the
 * suffix).
 */
export function normalizeInviteCode(raw: string): string {
  const cleaned = raw.replace(/\s+/g, "").toUpperCase();
  if (!cleaned) return "";
  if (cleaned.startsWith(CODE_PREFIX)) return cleaned;
  return `${CODE_PREFIX}${cleaned}`;
}

/**
 * Read-only check. Doesn't touch counters. Safe for unauthenticated
 * preflight calls (e.g. the /signup UI's "is my code valid?" hint).
 */
export async function validateInviteCode(code: string): Promise<ValidateResult> {
  const normalized = normalizeInviteCode(code);
  if (!normalized) return { valid: false, reason: "NOT_FOUND" };

  const row = await prisma.inviteCode.findUnique({
    where: { code: normalized },
    select: {
      id: true,
      maxUses: true,
      usedCount: true,
      expiresAt: true,
    },
  });
  if (!row) return { valid: false, reason: "NOT_FOUND" };
  if (row.expiresAt && row.expiresAt < new Date()) {
    return { valid: false, reason: "EXPIRED" };
  }
  if (row.usedCount >= row.maxUses) {
    return { valid: false, reason: "EXHAUSTED" };
  }
  return {
    valid: true,
    codeId: row.id,
    remainingUses: row.maxUses - row.usedCount,
  };
}

/**
 * Transactional redeem. Uses Prisma's $transaction with an interactive
 * callback so we can re-check the counter under the same DB connection
 * — preventing two concurrent signups from both pushing usedCount past
 * maxUses.
 *
 * Throws Error("INVITE_CODE_RACED") if a concurrent redeem won.
 */
export async function redeemInviteCode(codeId: string, userId: string): Promise<void> {
  await prisma.$transaction(async (tx) => {
    const row = await tx.inviteCode.findUnique({
      where: { id: codeId },
      select: { id: true, maxUses: true, usedCount: true, expiresAt: true },
    });
    if (!row) throw new Error("INVITE_CODE_NOT_FOUND");
    if (row.expiresAt && row.expiresAt < new Date()) {
      throw new Error("INVITE_CODE_EXPIRED");
    }
    if (row.usedCount >= row.maxUses) {
      throw new Error("INVITE_CODE_RACED");
    }
    await tx.inviteCode.update({
      where: { id: codeId },
      data: { usedCount: { increment: 1 } },
    });
    await tx.inviteCodeRedemption.create({
      data: { inviteCodeId: codeId, userId },
    });
  });
}

/**
 * Mint a fresh code. Retries on the (vanishingly rare) generated-code
 * collision so callers don't have to.
 */
export async function mintInviteCode(input: {
  mintedById?: string | null;
  note?: string | null;
  maxUses?: number;
  expiresAt?: Date | null;
}): Promise<{ code: string; id: string }> {
  const maxUses = Math.max(1, Math.floor(input.maxUses ?? 1));

  for (let attempt = 0; attempt < 5; attempt += 1) {
    const code = generateInviteCode();
    try {
      const row = await prisma.inviteCode.create({
        data: {
          code,
          mintedById: input.mintedById ?? null,
          note: input.note ?? null,
          maxUses,
          expiresAt: input.expiresAt ?? null,
        },
        select: { id: true, code: true },
      });
      return { id: row.id, code: row.code };
    } catch (err) {
      // P2002 = unique-constraint violation; retry with a fresh code.
      const prismaErr = err as { code?: string };
      if (prismaErr?.code !== "P2002") throw err;
    }
  }
  throw new Error("INVITE_CODE_MINT_RETRIES_EXHAUSTED");
}
